require("dotenv").config();
const fs = require("fs");
const path = require("path");
const { Client, GatewayIntentBits, EmbedBuilder } = require("discord.js");
const config = require("../config.json");

const client = new Client({
    intents: [
            GatewayIntentBits.Guilds,
                    GatewayIntentBits.GuildMessages,
                            GatewayIntentBits.MessageContent
                                ]
                                });

                                const dataPath = path.join(__dirname, "../data/gameData.json");

                                // 💾 Oyun verisini yükle
                                function loadData() {
                                    if (!fs.existsSync(dataPath)) {
                                            const defaultData = {
                                                        currentNumber: 1,
                                                                    lastUserId: null,
                                                                                boomNumbers: generateBoomNumbers(config.maxNumber)
                                                                                        };
                                                                                                fs.writeFileSync(dataPath, JSON.stringify(defaultData, null, 2));
                                                                                                        return defaultData;
                                                                                                            }
                                                                                                                return JSON.parse(fs.readFileSync(dataPath));
                                                                                                                }

                                                                                                                // 💾 Kaydet
                                                                                                                function saveData(data) {
                                                                                                                    fs.writeFileSync(dataPath, JSON.stringify(data, null, 2));
                                                                                                                    }

                                                                                                                    // 💣 Boom üretici (her 30 sayıda 2 tane)
                                                                                                                    function generateBoomNumbers(maxNumber) {
                                                                                                                        const boomNumbers = new Set();

                                                                                                                            for (let i = 1; i <= maxNumber; i += 30) {
                                                                                                                                    const start = i;
                                                                                                                                            const end = Math.min(i + 29, maxNumber);

                                                                                                                                                    let first = Math.floor(Math.random() * (end - start + 1)) + start;
                                                                                                                                                            let second;

                                                                                                                                                                    do {
                                                                                                                                                                                second = Math.floor(Math.random() * (end - start + 1)) + start;
                                                                                                                                                                                        } while (second === first);

                                                                                                                                                                                                boomNumbers.add(first);
                                                                                                                                                                                                        boomNumbers.add(second);
                                                                                                                                                                                                            }

                                                                                                                                                                                                                return Array.from(boomNumbers);
                                                                                                                                                                                                                }

                                                                                                                                                                                                                let gameData;

                                                                                                                                                                                                                client.once("ready", async () => {
                                                                                                                                                                                                                    console.log(`${client.user.tag} aktif!`);

                                                                                                                                                                                                                        gameData = loadData();

                                                                                                                                                                                                                            // Embed açılış mesajı → ilk allowed channel
                                                                                                                                                                                                                                for (const channelId of config.allowedChannels) {
                                                                                                                                                                                                                                        const channel = client.channels.cache.get(channelId);
                                                                                                                                                                                                                                                if (channel && channel.isTextBased()) {
                                                                                                                                                                                                                                                            const embed = new EmbedBuilder()
                                                                                                                                                                                                                                                                            .setColor("#00ff88")
                                                                                                                                                                                                                                                                                            .setTitle("💣 BOOM GAME BAŞLADI!")
                                                                                                                                                                                                                                                                                                            .setDescription("Sırayla sayı yazın! Yanlış yazarsanız silinir. Her 30 sayıda 2 BOOM var!")
                                                                                                                                                                                                                                                                                                                            .setImage("attachment://banner.png");

                                                                                                                                                                                                                                                                                                                                        await channel.send({
                                                                                                                                                                                                                                                                                                                                                        embeds: [embed],
                                                                                                                                                                                                                                                                                                                                                                        files: ["./assets/banner.png"]
                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                break; // sadece ilk kanala gönder
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                            client.on("messageCreate", async (message) => {
                                                                                                                                                                                                                                                                                                                                                                                                                if (message.author.bot) return;

                                                                                                                                                                                                                                                                                                                                                                                                                    // ✅ SADECE BU KANALLAR
                                                                                                                                                                                                                                                                                                                                                                                                                        if (!config.allowedChannels.includes(message.channel.id)) return;

                                                                                                                                                                                                                                                                                                                                                                                                                            const number = parseInt(message.content);
                                                                                                                                                                                                                                                                                                                                                                                                                                if (isNaN(number)) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                    // 🚫 Aynı kişi art arda yazamaz
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (message.author.id === gameData.lastUserId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                await message.delete().catch(() => {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ❌ Yanlış sayı
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (number !== gameData.currentNumber) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await message.delete().catch(() => {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 💣 BOOM
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (gameData.boomNumbers.includes(gameData.currentNumber)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await message.react("💣").catch(() => {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await message.channel.send(`💥 BOOM! ${message.author} patladı!`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gameData.currentNumber = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gameData.lastUserId = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        saveData(gameData);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ✅ Doğru sayı
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await message.react("✅").catch(() => {});

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gameData.lastUserId = message.author.id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gameData.currentNumber++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (gameData.currentNumber > config.maxNumber) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gameData.currentNumber = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gameData.lastUserId = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                saveData(gameData);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 🛡 Hata koruma
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                process.on("unhandledRejection", console.error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                process.on("uncaughtException", console.error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                client.login(process.env.TOKEN);